export const blogpost = [
{
    id: 1,
    title: "Introduction to Azure Fundamentals: A Beginner’s Guide",
    excerpt: "Imagine you need to run a powerful application, but your personal computer isn’t strong enough. Instead of buying expensive hardware, you can use cloud computing—where a company like Microsoft provides the necessary resources over the internet. Cloud computing allows businesses and individuals to access computing power, storage, and applications on demand, without the need for physical infrastructure.",
    date: "June 1, 2023",
    author: "Vihini Ranasingha",
    readTime: "5 min read",
    image: "/blog/1.jpg?height=500&width=250",
    category: "Cloud",
    mediumLink: "https://medium.com/@rvihini/introduction-to-azure-fundamentals-a-beginners-guide-6cf86486d29f",
    authorimage: "/blog/1.jpg?height=500&width=250",
  },
  {
    id: 2,
    title: "CI/CD Pipeline for Web App Deployment with Docker, Azure DevOps, and Azure Container Registry",
    excerpt: "Are you looking to deploy your Projects to Azure? With Azure DevOps, you can automate your app’s build and deployment processes with continuous integration (CI) and continuous deployment (CD). This guide will walk you through the steps to set up CI/CD pipelines for both the frontend and backend of your project. Let’s dive in!",
    date: "May 25, 2023",
    author: "Abishek Haththakage",
    readTime: "8 min read",
    image: "/blog/2.png?height=500&width=250",
    category: "Career",
    mediumLink: "https://medium.com/@abhixsh__/ci-cd-pipeline-for-web-app-deployment-with-docker-azure-devops-and-azure-container-registry-fd385042b755",
    authorimage: "/blog/1.jpg?height=500&width=250",
  },
  {
    id: 3,
    title: "Creating Your First Azure Virtual Machine: A Beginner’s Guide",
    excerpt: "In this article, I’ll walk you through creating an Azure Virtual Machine (VM) from scratch. Not only will you learn how to set up your VM, also, you’ll discover how to host a simple static web frontend such as a React web app from your GitHub repository on your newly created cloud virtual machine.",
    date: "May 18, 2023",
    author: "Theekshana Nirmal",
    readTime: "10 min read",
    image: "/blog/3.png?height=500&width=250",
    category: "Development",
    mediumLink: "https://theek.medium.com/creating-your-first-azure-virtual-machine-a-beginners-guide-3777540baeaa",
    authorimage: "/blog/1.jpg?height=500&width=250",
  },
  {
    id: 4,
    title: "A Beginner’s Guide: Deploying Your First Static Web Site using Azure App Services",
    excerpt: "Are you want to share your newly built static website (like a simple frontend) with the world? Azure App Service simplifies the deployment process, making it accessible even for those new to cloud platforms. In this article, I’ll guide you through the step-by-step process of deploying your site from a GitHub repository to Azure Static Web Apps. Let’s get started!",
    date: "May 10, 2023",
    author: "Theekshana Nirmal",
    readTime: "7 min read",
    image: "/blog/1.jpg?height=500&width=250",
    category: "Development",
    mediumLink: "https://theek.medium.com/a-beginners-guide-deploying-your-first-static-web-site-using-azure-app-services-400b303fd511",
    authorimage: "/blog/1.jpg?height=500&width=250",
  },
  {
    id: 5,
    title: "How to Create a Bastion Host for Secure Access to Private AWS Servers",
    excerpt: "A Bastion Host (also known as a Jump Host) is a special server used to securely access other computers or servers in a private network. It acts as a gateway to your internal resources, allowing only trusted users to enter the network.",
    date: "May 5, 2023",
    author: "Abishek Haththakage",
    readTime: "4 min read",
    image: "/blog/2.png?height=500&width=250",
    category: "Events",
    mediumLink: "https://medium.com/@abhixsh__/how-to-create-a-bastion-host-for-secure-access-to-private-aws-servers-b2e689c97f99",
    authorimage: "/blog/1.jpg?height=500&width=250",
  },
  {
    id: 6,
    title: "Provision an Azure Virtual Machine Using Terraform with Remote State and GitHub Actions",
    excerpt: "In this guide, I’ll show you how I used Terraform to create a Virtual Machine (VM) in Microsoft Azure, store the state remotely in Azure Storage, and automate the whole process using GitHub Actions.",
    date: "April 28, 2023",
    author: "Abishek Haththakage",
    readTime: "6 min read",
    image: "/blog/3.png?height=500&width=250",
    category: "AI",
    mediumLink: "https://medium.com/@abhixsh__/provision-an-azure-virtual-machine-using-terraform-with-remote-state-and-github-actions-41d80e042fa3",
    authorimage: "/blog/1.jpg?height=500&width=250",
  },
]

export const featuredPost = {
  id: 7,
  title: "A Beginner’s Guide: Deploying Your First Static Web Site using Azure App Services",
  excerpt: "Exploring how Microsoft's latest innovations are transforming the educational landscape and preparing students for the workforce of tomorrow.",
  date: "June 5, 2023",
  author: "Theekshana Nirmal",
  readTime: "12 min read",
  image: "/articles/art7.png?height=1200&width=600",
  category: "Education",
  mediumLink: "https://theek.medium.com/a-beginners-guide-deploying-your-first-static-web-site-using-azure-app-services-400b303fd511",
  authorimage: "/blog/1.jpg?height=500&width=250",
};

